pipeline{
   agent any 
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage('sonar-scan'){
        steps{
            withSonarQubeEnv('sonarQube'){
        sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=itsmartpen_geo-app'
            }
          
        
        }
    }
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }     
 
   
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP6Bdwx4zuzatzGgcxgbkd8vYRm -T \
            target/bio*.jar \
            "http://54.209.114.112:8081/artifactory/geosolution/file1/bio-${BUILD_ID}.jar"'
        }
    }


    stage('docker_login'){
        steps{
            sh 'aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin \
            140102337343.dkr.ecr.us-east-1.amazonaws.com'
        }
    }
       
    }
}
